### ISSUE TITLE
Locomotion Test 13-12-2023

### ISSUE THREAD

**Issue by Toprak-Efe** [Ozyegin-Planetary-Robotics-Laboratory/ozurover-locomotion#1]
# Erroneous Code
Running the script with Python3 yields the following error.
`exo@ubuntu:~/catkin_ws/src/ozurover-locomotion/python_script$ python3 main.py
/home/exo/.local/lib/python3.6/site-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.bindings.openssl.binding import Binding
main.py:161: UserWarning: 'ozurover-locomotion_8075_1702546216137' is not a legal ROS base name. This may cause problems with other ROS tools.
  rospy.init_node("ozurover-locomotion", anonymous=True)
Initializing device: AK70-10  ID: 1
Initializing CAN Manager
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 124, in telemetryTask
    "LocoMotorData": get_motor_collection_state(),
  File "main.py", line 110, in get_motor_collection_state
    for i, m in enumerate(motor_collection):
NameError: name 'motor_collection' is not defined
[sudo] password for exo: 
Connected on: <can.interfaces.socketcan.socketcan_native.SocketcanNative_Bus object at 0x7fa7f6ed68>
Traceback (most recent call last):
  File "main.py", line 164, in <module>
    with TMotorManager_servo_can(motor_type='AK70-10', motor_ID=1) as motor1:
  File "/home/exo/catkin_ws/src/ozurover-locomotion/python_script/TMotorCANControl/servo_can.py", line 631, in __init__
    self._canman.add_motor(self)
  File "/home/exo/catkin_ws/src/ozurover-locomotion/python_script/TMotorCANControl/servo_can.py", line 248, in add_motor
    self.notifier.add_listener(motorListener(self, motor))
AttributeError: 'Notifier' object has no attribute 'add_listener'`
Take note the nullity of the packages you were using at the time you wrote this code, you need to manually put them into the same workspace as your script. I fixed this and added them already, however, you should debug this code and fix all errors that appear.
The entire Rover is ready for constant testing, for a very long time, in fact. Come to the laboratory and begin work, I will be there too, excepting some hours of the day.
# Formatting
Your code is also difficult to read, uses unnecessary global variables. Use the methods of encapsulation in order to create a compact code that anyone can understand.

**Comment by Toprak-Efe** [comment]
You have wrapped up the errors I told of in here, well done. I am closing this. Code format is not a requirement, AI can rewrite it when it is good enough in the future.
